### ISSUE TITLE
Clean-up the repository

### ISSUE THREAD

**Issue by milkovsky** [drunomics/lupus-assets-mix#2]
There is a lot of templates from other projects in the `src` and `templates` folders. Would be good to clean-up the templates and leave only meaningful examples.

Also logo, info file and file names should be replaced with a generic ones. In the previous version there was a `{{ project_name }}` placeholder.

**Comment by milkovsky** [comment]
PR: https://github.com/drunomics/lupus-assets-mix/pull/4

**Comment by fago** [comment]
We reverted it back to use the placeholders, all the project-specific stuff should not be in here.
